version: "3.9"

services:

  database:
    container_name: database
    image: mysql:8.0.33
    restart: always
    env_file:
      - .env
    environment:
      MYSQL_DATABASE: springbootsecurityservicesuser
      MYSQL_USER: ${DATABASE_USERNAME}
      MYSQL_PASSWORD: ${DATABASE_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DATABASE_PASSWORD}
      MYSQL_ROOT_HOST: '%'
    volumes:
      - ./db:/var/lib/mysql
      - ./init.sql:/data/application/init.sql
    ports:
      - "3307:3306"
    command: --init-file /data/application/init.sql
    healthcheck:
      test: [ "CMD-SHELL", "mysqladmin ping -h localhost -u ${DATABASE_USERNAME} -p${DATABASE_PASSWORD}" ]
      interval: 20s
      timeout: 10s
      retries: 5
    networks:
      - springbootsecurityservicesuser

networks:
  springbootmicroservicesnetwork:
    driver: bridge