spring:
  config:
    activate:
      on-profile: dev

  datasource:
    url: ${POSTGRES_URL:jdbc:postgresql://localhost:5432/manager_expense}
    username: ${POSTGRES_USER:your_user}
    password: ${POSTGRES_PASSWORD:your_password}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        hbm2ddl:
          auto: update

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
openapi:
  service:
    api-docs: user-service
    server: http://localhost:${server.port}
    title: API Service
    description: API documents
    version: 1.0.0






