spring:
  main:
    lazy-initialization: true
    allow-bean-definition-overriding: true
  application:
    name: user_service
  data:
    mongodb:
      uri: mongodb+srv://root:4Klu3v8PktUHkPqN@cluster0.npjkp.mongodb.net/user
      auto-index-creation: true

  kafka:
    consumer:
      auto-offset-reset: earliest
      heartbeat-interval: 100
      group-id: user-repo
    producer:
      client-id: user-repo
    template:
      default-topic: root-topic
    bootstrap-servers: localhost:9092

server:
  port: 9001


